config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  as :admin do
    get '/admin', to: 'devise/sessions#new'
  end

  root 'main#index'

  resources :rooms

  resources :pools do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  resources :events do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  resources :testimonials

  resources :restaurants do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  match '/contacts', to: 'contacts#new', via: 'get'

  match '/piscina', to: 'pools#index', via: 'get'

  match '/evenimente', to: 'events#index', via: 'get'
  

  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :mail, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  def headers
    {
      :subject => "Mesaj Jadore",
      :to => "murinuareemail@gmail.com",
      :from => %("#{name}" <#{mail}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true

  has_attached_file :image,
    :styles => { medium: "600x600#", original: {convert_options: '-auto-orient'} }

  do_not_validate_attachment_file_type :image
end

app/models/pool.rb
class Pool < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def index
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Multumim pentru mesaj'
      redirect_to root_path
    else
      flash.now[:notice] = 'Mesajul nu a fost trimis, va rugam incercati din nou'
      render :new
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @pictures = Picture.where(attachable_type: 'Event')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new

    if @event.save
      if params[:images]
        params[:images].each { |image|
          @event.pictures.create(image: image)
        }
      end
      redirect_to events_path
    end
  end

  def delete
    @pictures = Picture.where(attachable_type: 'Event')
  end

  def destroy_pictures
    @pictures = Picture.where(id: params[:pictures_ids])
    @pictures.each do |picture|
      picture.destroy
    end

    redirect_to events_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @rooms = Room.all
    @testimonial = Testimonial.all
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    @pictures = Picture.where(attachable_type: 'Pool')
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.new

    if @pool.save
      if params[:images]
        params[:images].each { |image|
          @pool.pictures.create(image: image)
        }
      end
      redirect_to pools_path
    end
  end

  def delete
    @pictures = Picture.where(attachable_type: 'Pool')
  end

  def destroy_pictures
    @pictures = Picture.where(id: params[:pictures_ids])
    @pictures.each do |picture|
      picture.destroy
    end

    redirect_to pools_path
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @pictures = Picture.where(attachable_type: 'Restaurant')
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new

    if @restaurant.save
      if params[:images]
        params[:images].each { |image|
          @restaurant.pictures.create(image: image)
        }
      end
      redirect_to restaurants_path
    end
  end

  def delete
    @pictures = Picture.where(attachable_type: 'Restaurant')
  end

  def destroy_pictures
    @pictures = Picture.where(id: params[:pictures_ids])
    @pictures.each do |picture|
      picture.destroy
    end

    redirect_to restaurants_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_admin!, only: ['new', 'destroy', 'update', 'edit']
  def show
    @room = Room.find(params[:id])
    @random_rooms = Room.order("RANDOM()").limit(2)
  end

  def new
    @room = Room.new
  end

  def index
    @room = Room.all
  end

  def create
    @room = Room.new(room_params)
    if @room.save

      if params[:images]
        params[:images].each { |image|
          @room.pictures.create(image: image)
        }
      end
      redirect_to @room
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      if params[:images]
        params[:images].each { |image|
          @room.pictures.create(image: image)
        }
      end
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private
    def room_params
      params.require(:room).permit(:title, :images, :description, :facilities, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_page_class(path, page)
    if current_page?(path)
      return page
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pool_helper.rb
module PoolHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/contacts/new.html.haml
#subheader.contact-bg
  %h1 Contact
  %h3 Ramaneti conectati!
/ subheader close
#map-container
  %iframe{:frameborder => "0", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://www.google.com/maps/embed?pb=%211m23%211m12%211m3%211d89216.05692635482%212d21.850639242577422%213d45.67086460128687%212m3%211f0%212f0%213f0%213m2%211i1024%212i768%214f13.1%214m8%213e6%214m0%214m5%211s0x474fbecf1f73094d%3A0x92f01a1b6eb3e3dd%212sjadore+hotel+lugoj%213m2%211d45.670885999999996%212d21.920679%215e0%213m2%211sen%212sus%214v1488739388283;t=m&z=14&output=embed&iwloc=false"}
/ content begin
#content
  .container
    .row
      .col-md-8
        .col-md-12
          %h3 Trimiteti-ne un mesaj acum!
          Simtiti-va liberi sa ne contactati prin formularul de mai jos.
          %br/
          %br/
        .contact_form_holder
          = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
            .col-md-6
              = f.input :name, :placeholder => 'Numele si Prenumele', :type => 'text'
            .col-md-6
              = f.input :mail, :placeholder => 'Email', :type => 'text'
            .col-md-12
              = f.text_area :message, :placeholder => 'Mesajul', :cols => "100", :rows => "10"
              #mail_success.success
                Multumim! Mesajul a
                fost trimis!
              #mail_failed.error
                Eroare, mesajul nu a fost
                trimis!
              %p#btnsubmit
                = f.button :submit, 'Trimiteti', :class => "btn btn-custom"
      #sidebar.col-md-4
        / widget text
        .widget.widget-text
          %address
            %h4 J'adore Hotel
            %span Strada Caransebeșului nr.12
            %span
              Lugoj, Timis
              305500
            %span Tel: (40) 356 008 888
            %span
              Email:
              %a{:href => "mailto:contact@jadorehotel.com"} contact@jadorehotel.ro
          .small-border

app/views/events/_gallery.html.haml
.container
  .event-gallery.gallery-carousel
    - @pictures.each_slice(6) do |picture_slice|
      .item
        - picture_slice.each_with_index do |picture, index|
          .col-md-4
            %a.preview{"data-gal" => "prettyPhoto", :href => picture.image.url(:original)}
              %div{class: 'shape-'"#{index}"}
                = image_tag picture.image.url(:medium), class: 'img-responsive gallery-item'

app/views/events/_header_section.html.haml
#slider
  .callbacks_container
    %ul.rslides.pic_slider
      %li
        .text-wrap
          .inner.full-width
            .mid
              %h3 Noi dăm viață
              %h1 EVENIMENTULUI TĂU
        = image_tag 'events/header.jpg'

app/views/events/_text_section.html.haml
.text-restaurant-wrapper
  .clearfix
  .container
    .col-md-12.top-space
      %p.font-family-gabriola J’adore Events este localul ideal pentru organizarea de evenimente speciale(nunti,botezuri,petreceri tematice).Cu o capacitate de peste 450 de locuri.

app/views/events/_top_section.html.haml
.container-fluid
  .row
    = render 'header_section'
  .row
    = render 'gallery'
  .row
    = render 'text_section'

app/views/events/delete.html.haml
.container
  = form_tag destroy_pictures_events_path, method: :post do
    - @pictures.each do |picture|
      .row
        .col-md-12
          = check_box_tag 'pictures_ids[]', picture.id
          %a.preview{"data-gal" => "prettyPhoto", :href => picture.image.url(:original)}
            = image_tag picture.image.url(:medium)
    = submit_tag 'Delete Selected'

app/views/events/new.html.haml
.container
  %br
  = form_for @event, :html => { :class => '', multipart: true } do |p|
    .form-group
      = p.label :pictures, :class => 'control-label'
      = file_field_tag "images[]", type: :file, multiple: true
    .form-group
      = p.submit 'Adauga poze', class: 'btn btn-border'
  %br

app/views/pools/_bottom_section.html.haml
.container-fluid
  .row
    .pool-bottom-background
      .container-fluid
        .row.pool-first-row
          .col-md-6
            .row
              %h2.pool-gallery-text.blue-text-background.blue-text-background2 PISCINA NOSTRA
        .row.pool-forth-row
          .container
            .transparent-background.col-md-10.col-md-offset-1
              %p J’adore Boutique Hotel dispune, de o frumoasa piscina exterioara, ce te invita sa te relaxezi in zilele frumoase de vara. Te invitam cu drag sa incerci piscina hotelului J’adore, iar relaxarea este garantata.

app/views/pools/_top_section.html.haml
.container-fluid
  .row
    .pool-top-background
      .container
        .row.pool-first-row
          .col-md-4
            %h1.pool-heading PISCINA
            %h3.white-background.pool-sub-heading FII PREGATIT PENTRU VARA
        .row.pool-second-row
          .col-md-5
            %p.white-background.pool-top-text.pool-text.dark-blue-bg
              VENITI
          .col-md-8
            %p.white-background.pool-bottom-text.pool-text.light-blue-bg
              SA DESCOPERITI PISCINA NOASTRA
      .pool-third-row
        .col-md-6
          .row
            %h2.pool-gallery-text.blue-text-background GALERIE

app/views/pools/delete.html.haml
.container
  = form_tag destroy_pictures_pools_path, method: :post do
    - @pictures.each do |picture|
      .row
        .col-md-12
          = check_box_tag 'pictures_ids[]', picture.id
          %a.preview{"data-gal" => "prettyPhoto", :href => picture.image.url(:original)}
            = image_tag picture.image.url(:medium)
    = submit_tag 'Delete Selected'

app/views/pools/index.html.haml
= render 'top_section'
.pool-blue-section
  = render 'gallery'
= render 'bottom_section'

app/views/pools/new.html.haml
.container
  %br
  = form_for @pool, :html => { :class => '', multipart: true } do |p|
    .form-group
      = p.label :pictures, :class => 'control-label'
      = file_field_tag "images[]", type: :file, multiple: true
    .form-group
      = p.submit 'Adauga poze', class: 'btn btn-border'
  %br

app/views/restaurants/_gallery.html.haml
.container
  .event-gallery.gallery-carousel
    - @pictures.each_slice(12) do |picture_slice|
      .item
        - picture_slice.each do |picture|
          .col-md-3
            %a.preview{"data-gal" => "prettyPhoto", :href => picture.image.url(:original)}
              = image_tag picture.image.url(:medium), class: 'img-responsive gallery-item'

app/views/restaurants/delete.html.haml
.container
  = form_tag destroy_pictures_restaurants_path, method: :post do
    - @pictures.each do |picture|
      .row
        .col-md-12
          = check_box_tag 'pictures_ids[]', picture.id
          %a.preview{"data-gal" => "prettyPhoto", :href => picture.image.url(:original)}
            = image_tag picture.image.url(:medium)
    = submit_tag 'Delete Selected'

app/views/restaurants/index.html.haml
#subheader
  %h1 Restaurant
#content.no-top.no-bottom
  %section#explore-1.side-bg
    .container
      .row
        .col-md-12
          .inner-padding
            %p Te invitam sa te lasi codus de cele mai rafinate gusturi ale bucatariei internationale/nationale. Chef-ul Hotelului J’adore Lugoj isi propune sa suprinda mereu, clientii, placut. Mai jos ai cateva dintre preparatele exceptionale, realizate de echipa noastra.
            .small-border
    = render 'gallery'

app/views/restaurants/new.html.haml
.container
  %br
  = form_for @restaurant, :html => { :class => '', multipart: true } do |p|
    .form-group
      = p.label :pictures, :class => 'control-label'
      = file_field_tag "images[]", type: :file, multiple: true
    .form-group
      = p.submit 'Adauga poze', class: 'btn btn-border'
  %br

app/views/rooms/_form.html.haml
.container
  = form_for @room, :html => { :class => '', multipart: true } do |r|
    .form-group
      = r.label :title
      = r.text_field :title, class: 'form-control'
    .form-group
      = r.label :facilities
      %br
      = r.label 'Adaugati facilitati separate printr-o virgula'
      = r.text_field :facilities, class: 'form-control'
    .form-group
      = r.label :link
      = r.text_field :link, class: 'form-control'
    .form-group
      = r.label :description
      = r.text_area :description, class: 'form-control'
    .form-group
      = r.label :pictures, :class => 'control-label'
      = file_field_tag "images[]", type: :file, multiple: true
    .form-group
      = r.submit 'Submit', class: 'btn btn-border'

app/views/rooms/edit.html.haml
= render 'rooms/form'

app/views/rooms/index.html.haml
#content
  .container
    .row.room-list
      .col-md-12
        - @room.each do |room|
          .room-item-alt
            .col-md-5
              -if room.pictures.first.present?
                = image_tag room.pictures.first.image.url(:medium)
              -else
                = image_tag 'room/pic1.jpg'
            .col-md-5
              .desc
                = link_to room_path(room) do
                  %h1
                    = room.title
                %p
                  = room.description
            .col-md-2.text-center
              = link_to 'Stergeti camera', room_path(room), class: 'btn btn-border', method: :delete, data: { confirm: 'Sunteti sigur?' }
              %br
              %br
              = link_to 'Editati camera', edit_room_path(room), class: 'btn btn-border'
            .clearfix

app/views/rooms/new.html.haml
= render 'rooms/form'

app/views/rooms/show.html.haml
#subheader
  %h3 Camera
  %h1
    = @room.title
#content
  .container
    .row
      .room-single
        .col-md-8
          %ul.slides.single-room-carousel
            - if @room.pictures.present?
              - @room.pictures.each do |picture|
                %li
                  = image_tag picture.image.url(:medium), class: 'img-responsive'
        .col-md-4
          .inner
            .text
              %h4 Prezentare
              %p
                = @room.description
              .room-specs
                %h4 Facilitati
                %ul
                  - @room.facilities.split(',').each do |facility|
                    %li
                      = facility
            = link_to 'Rezerva acum', @room.link, class: 'btn btn-border'
    %hr/
    .row
      - @random_rooms.each do |random_room|
        -if random_room.pictures.present?
          .col-md-6
            .room-item.item
              .overlay
                = link_to random_room do
                  %h1
                    = random_room.title
                .desc
                  = random_room.description
                  .price
                    %span
                  = link_to 'Vedeti Detalii', random_room, class: 'btn btn-border'
              = image_tag random_room.pictures.first.image.url(:medium)