config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  as :admin do
    get '/admin', to: 'devise/sessions#new'
  end

  root 'main#index'

  resources :rooms

  resources :pools do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  resources :events do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  resources :testimonials

  resources :restaurants do
    get 'delete', on: :collection
    post 'destroy_pictures', on: :collection
  end

  match '/contacts', to: 'contacts#new', via: 'get'

  match '/piscina', to: 'pools#index', via: 'get'

  match '/evenimente', to: 'events#index', via: 'get'
  

  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :mail, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  def headers
    {
      :subject => "Mesaj Jadore",
      :to => "murinuareemail@gmail.com",
      :from => %("#{name}" <#{mail}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true

  has_attached_file :image,
    :styles => { medium: "600x600#", original: {convert_options: '-auto-orient'} }

  do_not_validate_attachment_file_type :image
end

app/models/pool.rb
class Pool < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :pictures, as: :attachable, :dependent => :destroy
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @pictures = Picture.where(attachable_type: 'Event')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new

    if @event.save
      if params[:images]
        params[:images].each { |image|
          @event.pictures.create(image: image)
        }
      end
      redirect_to events_path
    end
  end

  def delete
    @pictures = Picture.where(attachable_type: 'Event')
  end

  def destroy_pictures
    @pictures = Picture.where(id: params[:pictures_ids])
    @pictures.each do |picture|
      picture.destroy
    end

    redirect_to events_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @rooms = Room.all
    @testimonial = Testimonial.all
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    @pictures = Picture.where(attachable_type: 'Pool')
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.new

    if @pool.save
      if params[:images]
        params[:images].each { |image|
          @pool.pictures.create(image: image)
        }
      end
      redirect_to pools_path
    end
  end

  def delete
    @pictures = Picture.where(attachable_type: 'Pool')
  end

  def destroy_pictures
    @pictures = Picture.where(id: params[:pictures_ids])
    @pictures.each do |picture|
      picture.destroy
    end

    redirect_to pools_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_admin!, only: ['new', 'destroy', 'update', 'edit']
  def show
    @room = Room.find(params[:id])
    @random_rooms = Room.order("RANDOM()").limit(2)
  end

  def new
    @room = Room.new
  end

  def index
    @room = Room.all
  end

  def create
    @room = Room.new(room_params)
    if @room.save

      if params[:images]
        params[:images].each { |image|
          @room.pictures.create(image: image)
        }
      end
      redirect_to @room
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      if params[:images]
        params[:images].each { |image|
          @room.pictures.create(image: image)
        }
      end
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private
    def room_params
      params.require(:room).permit(:title, :images, :description, :facilities, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_page_class(path, page)
    if current_page?(path)
      return page
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pool_helper.rb
module PoolHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Jadore Hotel - Hotel Lugoj
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: "#{add_page_class(piscina_path, 'pool-page')} #{add_page_class(evenimente_path, 'event-page')} #{add_page_class(restaurants_path, 'restaurant-page')}"}
    = render 'partials/header'
    = yield
    = render 'partials/footer'

app/views/partials/_footer.html.haml
%footer
  .container
    .row
      .col-md-4
        %h3
          = image_tag 'logo.png', :style => "width: 182px; height: 86px;"
        %h3
        Hotelul J'adore Boutique se află în orașul Lugoj din judeţul Timiş. Oferă piscină sezonieră în aer liber şi terasă. Oaspeții pot lua masa la restaurant. Există parcare privată gratuită.
      .col-md-4
        %h3 Social Media
        .social-icons
          %a{:href => "https://www.facebook.com/jadoreboutiquehotel/?fref=ts"}
            = image_tag 'social-icons/facebook.png'
        .clearfix
      .col-md-4
        %h3 Adresa
        %address
          %span J'adore Hotel
          %span
            Strada Caransebeșului
            nr.12
          %span Lugoj, Timis 305500
          %span
            Tel:
            %a{:href => "tel:0356008888"} (40) 356 008 888
          %span
            Email:
            %a{:href => "mailto:contact@jadorehotel.com"} contact@jadorehotel.ro
  .subfooter
    .container
      .row
        .col-md-6
          © Copyright 2017 -
          %span{:style => "color: #888888;"}>
          Toate drepturile rezervate J’adore Hotel. Dezvoltat de
          %a{:href => "http://holdmarketing.ro/"}
            Hold Marketing
        .col-md-6
          %nav
            %ul
              %li
                = link_to 'Acasa', '/'
              %li
                = link_to 'Piscina', piscina_path
              %li
                = link_to 'Restaurant', restaurants_path
              %li
                = link_to 'Sala de evenimente', evenimente_path
              %li
                = link_to 'Booking', 'https://www.booking.com/hotel/ro/j-39-adore-boutique.ro.html'
              %li
                = link_to 'Contact', contacts_path

app/views/partials/_header.html.haml
%header
  - if admin_signed_in?
    .container-fluid
      .admin-menu
        %span
          = link_to 'Camera noua', new_room_path
        %span
          = link_to 'Toate camerele', rooms_path
        %span
          = link_to 'Adauga poze piscina', new_pool_path
        %span
          = link_to 'Sterge poze piscina', delete_pools_path
        %span
          = link_to 'Adauga poze restaurant', new_restaurant_path
        %span
          = link_to 'Sterge poze restaurant', delete_restaurants_path
        %span
          = link_to 'Adauga poze evenimente', new_event_path
        %span
          = link_to 'Sterge poze evenminete', delete_events_path
        %span
          = link_to 'Testimoniale', testimonials_path

        = link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'pull-right'
  #logo
    .inner
      %a{:href => "/"}
        = image_tag 'logo.png'
  #mainmenu-container
    %ul#mainmenu
      %li
        = link_to 'Acasa', '/'
      %li
        = link_to 'Piscina', piscina_path
      %li
        = link_to 'Restaurant', restaurants_path
      %li
        = link_to 'Sala de evenimente', evenimente_path
      %li
        = link_to 'Booking', 'https://www.booking.com/hotel/ro/j-39-adore-boutique.ro.html'
      %li
        = link_to 'Contact', contacts_path
  #menu-btn